### PR TITLE
Update Forc.toml

### PR DESCRIPTION
**Pull request by Budalebah**
v0.5.1

## Type of change

- Bug fix
- New feature
- Improvement (refactoring, restructuring repository, cleaning tech debt, ...)
- Documentation
- Other (describe below)

## Changes

The following changes have been made:

- Change 1
- Change 2

## Notes

- Note 1

## Related Issues

Closes #\<issue number\>

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.
- [x] I have updated the changelog to reflect the changes on this PR.

### CODE REVIEW

**Comment by Budalebah** [comment]
sorry i didnt understand

**Comment by Budalebah** [comment]
Sorry i dont understand @bitzoic

**Comment by K1-R1** [comment]
Hi @Budalebah, we encourage all contributions but we will not be able to merge this PR in it's current form as updating the `Forc.toml` manifest must be accompanied by re-building the libs so that the `Forc.lock` file is also updated. Typically we update dependencies when we need to as opposed to whenever the latest version arrives, however I will leave it to you to decide if you want to close this PR or rebuild the libs

**Comment by Budalebah** [comment]
I will do it

**Comment by bitzoic** [comment]
Closed in https://github.com/FuelLabs/sway-libs/pull/281

**Pull request closed without merging**
