### PR TITLE
Update to forc 0.63.3 and fuel-rs 0.66.2

### LINKED ISSUE #288: Update to forc 0.63.3 and fuel-rs 0.66.2

### PR DESCRIPTION
**Pull request by K1-R1**
## Type of change

- Improvement (refactoring, restructuring repository, cleaning tech debt, ...)

## Changes

The following changes have been made:

- Update to forc 0.63.3 and fuel-core 0.34.0
- Update to fuel-rs 0.66.2

## Notes

- Bytecode tests are currently failing

## Related Issues

Closes #288 

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [x] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.
- [x] I have updated the changelog to reflect the changes on this PR.

### CODE REVIEW

**Comment by K1-R1** [comment]
To be merged after #286

**Comment by K1-R1** [comment]
The tests for the Bytecode library currently fail and require fixing

**Review by bitzoic — APPROVED** [review]

**Review by SwayStar123 — APPROVED** [review]
Why is the fuel-core-lib feature removed from the crate import?

**Comment by bitzoic** [comment]
> Why is the fuel-core-lib feature removed from the crate import?

Fuel-core is now dictated by CI and uses the correct wasm target.

**Pull request merged**
